### ISSUE TITLE
gorilla integration with visual studio 2015 not working

### ISSUE THREAD

**Issue by Bobrovskiy** [UXDivers/Gorilla-Player-Support#109]
GorillaVS Error: 3 : Exception 'Object reference not set to an instance of an object.' ocurred while doing 'Preferences property changed (addin)'. Trace    at UXDivers.Artina.Player.Addins.GorillaPlayerPackage.TearDownFollowMe() in C:\UXDivers\gorilla\source\Addins\VS\GorillaVSAddin\GorillaPlayerPackage.cs:line 300
   at UXDivers.Artina.Player.Addins.GorillaPlayerPackage.<PreferencesPropertyChangedHandler>d__10.MoveNext() in C:\UXDivers\gorilla\source\Addins\VS\GorillaVSAddin\GorillaPlayerPackage.cs:line 266.
    ProcessId=5900
    DateTime=2016-06-14T10:21:54.7077648Z
    Timestamp=124408310215

GorillaVS Error: 21 : Exception 'Unable to connect to the remote server' ocurred while doing 'IsServerAvailable(http://localhost:9014/)'. Trace    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UXDivers.Artina.Player.Addins.Backend.<InvokeServer>d__42`1.MoveNext() in C:\UXDivers\gorilla\source\Addins\XS\XamarinAddin\Server\Backend.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UXDivers.Artina.Player.Addins.Backend.<IsServerAvailable>d__32.MoveNext() in C:\UXDivers\gorilla\source\Addins\XS\XamarinAddin\Server\Backend.cs:line 176.
    ProcessId=2208
    DateTime=2016-06-14T10:06:45.2614606Z
    Timestamp=122458840662

**Comment by Bobrovskiy** [comment]
{"level":"info","message":"Gorilla Server: info: Solution not found\r\n","timestamp":"2016-06-14T10:31:48.540Z"}
{"level":"info","message":"Gorilla Server: info: Adding solution (from VS - 14.0): D:\\Gorilla\\Samples\\MyCoolCompanyApp\\MyCoolCompanyApp.sln \r\n","timestamp":"2016-06-14T10:31:48.547Z"}
{"level":"info","message":"Gorilla Server: info: Setting Target: MyCoolCompanyPage.xaml (d:\\Gorilla\\Samples\\MyCoolCompanyApp\\MyCoolCompanyApp\\MyCoolCompanyApp.csproj) requested from VS (14.0)\r\n","timestamp":"2016-06-14T10:31:49.743Z"}
{"level":"info","message":"Gorilla Server: info: Solution not found\r\n","timestamp":"2016-06-14T10:31:49.743Z"}
{"level":"info","message":"Gorilla Server: info: Adding solution (from VS - 14.0): D:\\Gorilla\\Samples\\MyCoolCompanyApp\\MyCoolCompanyApp.sln \r\n","timestamp":"2016-06-14T10:31:49.748Z"}
{"level":"info","message":"Gorilla Server: info: Setting Target: MyCoolCompanyPage.xaml (d:\\Gorilla\\Samples\\MyCoolCompanyApp\\MyCoolCompanyApp\\MyCoolCompanyApp.csproj) requested from VS (14.0)\r\n","timestamp":"2016-06-14T10:31:50.766Z"}
{"level":"info","message":"Gorilla Server: info: Solution not found\r\n","timestamp":"2016-06-14T10:31:50.766Z"}
{"level":"info","message":"Gorilla Server: info: Adding solution (from VS - 14.0): D:\\Gorilla\\Samples\\MyCoolCompanyApp\\MyCoolCompanyApp.sln \r\n","timestamp":"2016-06-14T10:31:50.768Z"}
{"level":"info","message":"Gorilla Server: info: Setting Target: MyCoolCompanyPage.xaml (d:\\Gorilla\\Samples\\MyCoolCompanyApp\\MyCoolCompanyApp\\MyCoolCompanyApp.csproj) requested from VS (14.0)\r\n","timestamp":"2016-06-14T10:31:51.844Z"}
{"level":"info","message":"Gorilla Server: info: Solution not found\r\n","timestamp":"2016-06-14T10:31:51.844Z"}
{"level":"info","message":"Gorilla Server: info: Adding solution (from VS - 14.0): D:\\Gorilla\\Samples\\MyCoolCompanyApp\\MyCoolCompanyApp.sln \r\n","timestamp":"2016-06-14T10:31:51.928Z"}
{"level":"info","message":"Gorilla Server: info: Setting Target: MyCoolCompanyPage.xaml (d:\\Gorilla\\Samples\\MyCoolCompanyApp\\MyCoolCompanyApp\\MyCoolCompanyApp.csproj) requested from VS (14.0)\r\n","timestamp":"2016-06-14T10:31:52.941Z"}
{"level":"info","message":"Gorilla Server: info: Solution not found\r\n","timestamp":"2016-06-14T10:31:52.941Z"}
{"level":"info","message":"Gorilla Server: info: Adding solution (from VS - 14.0): D:\\Gorilla\\Samples\\MyCoolCompanyApp\\MyCoolCompanyApp.sln \r\n","timestamp":"2016-06-14T10:31:52.944Z"}

**Comment by LeoHere** [comment]
Hi, does the addin previously works for you or is it the first time you install it? If you try to connect from the "Gorilla Player Status" (available from View->Other Windows), does it gives you an error or you can actually connect?

**Comment by Bobrovskiy** [comment]
When I try to do Follow me or Stick to XAML
I receive message, see attachment

**Comment by LeoHere** [comment]
Hi @Bobrovskiy, I think the issue you are experience has nothing to do with VS. There seem to be an issue in the way path are compared in windows, that is the cause of the problem. As soon as we have the issue fixed I will let you know.

**Comment by Bobrovskiy** [comment]
thank you

**Comment by gppraveena** [comment]
Any updates on this issue, has this been fixed ? I am facing this problem on Win 10 and Win 7 seem to be showing the connected status, but it is not showing the preview
