### ISSUE TITLE
Gorilla server won't start (any more)

### ISSUE THREAD

**Issue by 0rupp** [UXDivers/Gorilla-Player-Support#171]
I tried rebooting, re-installing, but it only flickers up for the blink of an eye and closes again. The logs says:

{"level":"info","message":"Starting Gorilla (0.9.1.2)...","timestamp":"2016-10-08T10:23:19.443Z"}
{"level":"error","message":"Error reading license file ENOENT, no such file or directory 'C:\\Users\\Lap\\.gorilla\\license' Error: ENOENT, no such file or directory 'C:\\Users\\Lap\\.gorilla\\license'\n    at Object.fs.openSync (fs.js:449:16)\n    at Object.fs.readFileSync (fs.js:286:11)\n    at Object.result.verifyLicense (C:\\Program Files (x86)\\Gorilla Player\\resources\\LicenseHelper.js.jx:102:30)\n    at Object.result.currentUser (C:\\Program Files (x86)\\Gorilla Player\\resources\\LicenseHelper.js.jx:84:18)\n    at Object.<anonymous> (C:\\Program Files (x86)\\Gorilla Player\\resources\\Starter.js.jx:125:23)\n    at Module._compile (module.js:595:24)\n    at readX (module.js:1488:3)\n    at Object.Module._extensions..jx (module.js:1921:8)\n    at Module.load (module.js:416:30)\n    at Function.Module._load (module.js:380:8)\n    at Module.require (module.js:451:15)\n    at require (module.js:469:13)\n    at Object.<anonymous> (_jx_source:17:1)\n    at Module._compile (module.js:595:24)\n    at Module.load (module.js:425:6)\n    at Function.Module._load (module.js:380:8)","timestamp":"2016-10-08T10:23:19.460Z"}

I tried creating an empty license file, then the second log error disappears, however, the problem remains.
Using W10, latest version of gorilla, VS2015 (though not even opened)

**Comment by LeoHere** [comment]
Please try as follows:
1. Quit Gorilla
2. Delete the license file
3. Start gorilla again
4. Signin

Once you signin it will automatically create the license file again.

**Comment by 0rupp** [comment]
This doesn't work.
1. No need to quit, cos I cannot start anyway (I also checked the processes)
2. OK, I deleted it, but the problem is, it wasn't there in the first place.
3. Doesn't start.
4. Thus can't sign in

**Comment by LeoHere** [comment]
Did you had gorilla working previously in that machine? Or is it the first time you install gorilla there?

**Comment by 0rupp** [comment]
I had it installed for a while and it worked like a charm. Can't see why it stopped working now. The only thing that comes into my mind was the huge w10 update about 2 weeks ago.

**Comment by LeoHere** [comment]
That is weird.

If possible, can you try to:
* uninstall Gorilla
* delete the directory ```C:\Users\Lap\.gorilla\``` (just in case may be it is better to move it elsewhere or rename it so you don't loose the logs you have there)
* restart your machine (just to make sure there is nothing hanging there)
* reinstall Gorilla

If that does not work, can you send the all the logs generated after the fresh install to l r o d r i g u e z at u x d i v e r s . c o m
