### ISSUE TITLE
An error while building Derivedpages project in Gorilla\samples

### ISSUE THREAD

**Issue by jerryno6** [UXDivers/Gorilla-Player-Support#278]
Hi Gorilla team !

I had an error as the description below.
I've just downloaded gorila to my PC , installed it. I could see the UI changed while I was editing axml files as long as I built and run some projects such as 
Gorilla\Player.sln
Gorilla\Samples\HowTo\ContentView\ContentView.sln
Gorilla\Samples\HowTo\MyCoolCompanyApp\MyCoolCompanyApp.sln

Problem occured when I turned to **\Gorilla\Samples\HowTo\DerivedPages\DerivedPages.sln** 
while I was trying to build project "DerivedPages.Droid". I got this error while VS was biulding the project.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Collections.Immutable, Version=1.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'System.Collections.Immutable.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	DerivedPages.Droid			

I use Windows 10 Pro version 1709, OS Build 16299.309
Visual Studio Community 2017 15.6.2
Device: Asus zenfone 3 max (ZC553kl) which uses Android 7.1
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_152

**Comment by AliAkbarMontazeri** [comment]
In my case (and looks like you have a similar case with me) I read that I'm missing file 'System.Collections.Immutable.dll' so I googled '**system.collections.immutable.dll file**' which bring me to nuget [site](https://www.nuget.org/packages/System.Collections.Immutable/1.5.0-rc1), copy the installation command there and **run it on PM console** and then I did **Clean All -> Rebuild All -> Build All**.

Hope this helps.
