### ISSUE TITLE
Error resolving assembly

### ISSUE THREAD

**Issue by No1e** [UXDivers/Gorilla-Player-Support#290]
Hi, 

I've just migrate my project to .net standard 2.0, update Gorilla Player to 1.2 as well as SDK.
I am getting error while trying to preview xaml. Here is log:

{"level":"debug","message":"[Server] About to process package BouncyCastle (1.8.2). contextInstanceId=3, targetId=0, sampleDataId=0\r\ndebug: Package BouncyCastle (1.8.2) resolution for target framework \"netstandard2.0\": package folder \"E:\\...\\packages\\BouncyCastle.1.8.2\" and lib folder \"E:\\...\\packages\\BouncyCastle.1.8.2\\lib\\BouncyCastle.Crypto.dll\". contextInstanceId=3, targetId=0, sampleDataId=0\r\nerror: Xaml processing error Summary:\"Error resolving assemblies for BouncyCastle\"; Message:\"Error resolving assemblies for package \"BouncyCastle\" (ENOTDIR, not a directory 'E:\\...\\packages\\BouncyCastle.1.8.2\\lib\\BouncyCastle.Crypto.dll').\" processingIssue=true, issueType=error, position=null, area=Gral, scope=Sol, name=Error, message=ENOTDIR, not a directory 'E:\\...\\packages\\BouncyCastle.1.8.2\\lib\\BouncyCastle.Crypto.dll', stack=Error: ENOTDIR, not a directory 'E:\\...\\packages\\BouncyCastle.1.8.2\\lib\\BouncyCastle.Crypto.dll'\n    at Object.fs.readdirSync (fs.js:717:16)\n    at Object.parser._loadSinglePackageAssemblies (C:\\Users\\novak savic\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\SolutionParser.js.jx:588:40)\n    at Object.parser._loadSinglePackageAssembliesAsyncHelper (C:\\Users\\novak savic\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\SolutionParser.js.jx:730:18)\n    at Object.<anonymous> (C:\\Users\\novak savic\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\SolutionParser.js.jx:738:26)\n    at Object.parser._loadSinglePackageAssembliesAsyncHelper (C:\\Users\\novak savic\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\SolutionParser.js.jx:726:17)\n    at Object.<anonymous> (C:\\Users\\novak savic\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\SolutionParser.js.jx:710:26)\n    at DuplexWrapper.emit (events.js:98:14)\n    at endReadableNT (C:\\Users\\novak savic\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\node_modules\\unzipper\\node_modules\\readable-stream\\lib\\_stream_readable.js.jx:921:12)\n    at afterTickTwo (C:\\Users\\novak savic\\AppData\\Local\\Programs\\Gorilla Player\\1.2.0\\resources\\node_modules\\unzipper\\node_modules\\readable-stream\\node_modules\\process-nextick-args\\index.js.jx:26:10)\n    at process._tickCallback (node.js:803:1), contextInstanceId=3, targetId=0, sampleDataId=0\r\n","timestamp":"2018-05-03T06:28:41.066Z"}

Note I replace part of path with ... (too long path making log less readable).

Regards,
Novak

**Comment by No1e** [comment]
Hi,

Can you give me any help with this?

Regards,
Novak
